[package]
name = "telegram_bot"
version = "0.1.0"
edition = "2018"

[dependencies]
teloxide = { version = "0.7", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
dotenv = "0.15"
